### ISSUE TITLE
登录信息

### ISSUE THREAD

**Issue by ShiningMagicEye1** [jsanhuo/HotelManagementSystem#12]
老哥，这个登录的信息在哪里查找啊，没找到呀

**Comment by ShiningMagicEye1** [comment]
![Uploading login.jpg…]()

**Comment by ShiningMagicEye1** [comment]
![image](https://github.com/jsanhuo/HotelManagementSystem/assets/105256105/c6bf0998-90d7-4f76-a87f-0c60b6a8d362)

**Comment by jsanhuo** [comment]
数据库里加一个试试
